GET http://localhost:3000/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTkzMTdhYWFhNmJlNzU3ZjU5NDVkMiIsImlhdCI6MTcxMjkyNzEyNX0.ja3l5qtBR87LZ1NjPBon4KPU6NsusHqSHuNB8J08f9U