POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "cammelo@example.com", 
    "password": "salvesalvino123" 
}

###

# mimmo access token (user):
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MThkN2Y0NmU5NmJiZmZkOThjZjZlZCIsImlhdCI6MTcxMjkwNDI4NX0.Zzlq0oZst5-mRueC4zZmaEDzz8Nw-Fvp7DgAt_CYo5s

# superMimmo access token (admin):
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MThkODI3NmU5NmJiZmZkOThjZjZmMSIsImlhdCI6MTcxMjkwNDI1NH0.mPRywYcITGjkPMkglxisL_PjJC0oj14QMVTKpxuvQrc

#cammelo user
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTkyYTA0NTRkZWMyMjE5ZGY3ZGEzOSIsImlhdCI6MTcxMjkyNTIwOH0.RzHygVFcHfi8Mk_THPhUSnsHRqZRNCd_0AiXCyRngYE