POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin@vinylshop.com", 
    "password": "salvesalvino123" 
}

###

# mimmo access token (user):
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTkzMTE2YWFhNmJlNzU3ZjU5NDVjOCIsImlhdCI6MTcxMjkyNzA1Mn0.aYZE1lfxZsAJ_L6yyL6XGs0SZBbQ2q9ssHcnUrg38_Y

# superMimmo access token (admin):
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTkzMTdhYWFhNmJlNzU3ZjU5NDVkMiIsImlhdCI6MTcxMjkyNzEyNX0.ja3l5qtBR87LZ1NjPBon4KPU6NsusHqSHuNB8J08f9U