GET http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTdiNzdjMzJjYTk5MzQ5NTMxYmIyNSIsImlhdCI6MTcxMjgzMDY4Mn0.PdxSmuR3BMeVvEfJLt_kckmhSwNgWuV_wyFcGiYD5Bg