POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTUzZTFlMmQ5NGFjMjZhYTk3NGFlYiIsImlhdCI6MTcxMjg1OTkzN30.dZ1R_uB9plOGO_4II8b2RM2ILapM0DGzDn4T0wMCIcA

{
    "name": "lp3",
    "description": "description3",
    "price": 15.20,
    "stockQuantity": 20,
    "stockStatus": "in stock",
    "category": ["hip-hop","techno"]
}