PUT http://localhost:3000/api/products/6618daba10f0be594997347c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MThkODI3NmU5NmJiZmZkOThjZjZmMSIsImlhdCI6MTcxMjkwNDI1NH0.mPRywYcITGjkPMkglxisL_PjJC0oj14QMVTKpxuvQrc

{   
    "name": "lp4",
    "description": "description4",
    "price": 25.05,
    "stockQuantity": 15,
    "stockStatus": "in stock",
    "category": ["folk","liscio"]
}

###
