POST http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTkyYTA0NTRkZWMyMjE5ZGY3ZGEzOSIsImlhdCI6MTcxMjkyNTIwOH0.RzHygVFcHfi8Mk_THPhUSnsHRqZRNCd_0AiXCyRngYE

{
		"name": "Cammelo",
		"surname": "Modem",
		"addressLine": "Via Plebby",
		"zipCode": "95128",
		"city": "Satania",
		"country": "Satania",
		"state": "ST"
}