POST http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTdlYmNkMDg4MjI4MzYxYWExZjlmMCIsImlhdCI6MTcxMjg0MzkxOX0.OsuMAnTZLg7GPNbO_JHMSQzJUGeYf7G-t6VHybI0ZYw

{
		"name": "Mimmo",
		"surname": "Modem",
		"addressLine": "Via Plebby",
		"zipCode": "95128",
		"city": "Satania",
		"country": "Satania",
		"state": "ST"
}