DELETE http://localhost:3000/api/cart/remove/6617ef8d088228361aa1fa06 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTdlYmNkMDg4MjI4MzYxYWExZjlmMCIsImlhdCI6MTcxMjg0MzkxOX0.OsuMAnTZLg7GPNbO_JHMSQzJUGeYf7G-t6VHybI0ZYw
###