GET http://localhost:3000/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTkyZDVlMDU1NGJlMWZjM2Q2NjAzZiIsImlhdCI6MTcxMjkyNjA2N30.Oe4IvwI4IHXvTGfkv9gr6AM1JMgBITHmTo80QCZewlo

###