GET http://localhost:3000/api/cart HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTU0NDU4MTdkNTljOGE1Mzg4OTUzNSIsImlhdCI6MTcxMjY4MzA4NX0.bdU_IMDlz7MgX7AX9fjJohIwuMEvDHSRcCUWtV1O3Zk

###
